In [1]:
import json
import string
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

%matplotlib inline
warnings.filterwarnings("ignore")

In [2]:
#Dados 
df = pd.read_csv('data/gincanaV_SinistroFinal.csv', sep=",")
df.head(10)

,IDHM,IDHM_E,IDHM_L,IDHM_R,I_ESCOLARIDADE,Mes,anosFidelidadeCliente,codigoAgravamentoPremio,codigoCategoriaTarifaria,codigoClasseBonus,...,quantidadeUtilizacaoEstapar,renovou,resgatePontos,sexoSegurado,tipoPessoaSegurado,valorDiferencaPremioAnual,valorFranquia,valorImportanciaSeguradaCasco,valorPremioFinal,valorPremioPagoAtual
0,0.578,0.363,0.730,0.729,0.365,3,2,0,10,10,...,0,NaN,0,1,1,933.00000,935.0,32076.0,839.7000,1263.210000
1,0.702,0.581,0.786,0.756,0.487,3,2,0,11,1,...,0,NaN,0,1,1,2022.98000,3480.0,20252.0,1921.8300,3850.400000
2,0.624,0.470,0.759,0.680,0.368,3,7,0,10,5,...,0,NaN,1,0,1,1680.48350,3870.0,19080.0,1571.2525,1825.660000
3,0.702,0.581,0.786,0.756,0.487,3,9,0,10,8,...,0,NaN,0,1,1,1796.34000,1884.0,42898.0,1796.3400,2554.540000
4,0.440,0.242,0.617,0.569,0.251,3,4,0,10,8,...,0,NaN,1,1,1,1223.12500,1847.0,36047.0,1131.3930,1241.230000
5,0.578,0.363,0.730,0.729,0.365,3,4,0,10,10,...,0,NaN,0,1,1,1276.10000,1954.0,60519.0,1276.1000,1434.400000
6,0.578,0.363,0.730,0.729,0.365,3,8,0,10,9,...,0,NaN,0,1,1,572.79000,1085.0,14588.0,515.5100,911.040000
7,0.783,0.719,0.845,0.789,0.629,3,1,0,11,0,...,2,NaN,0,0,0,5043.14000,4040.0,150325.0,4286.6700,4551.850000
8,0.702,0.581,0.786,0.756,0.487,3,1,0,23,10,...,0,NaN,0,1,1,1150.62038,4777.0,73399.0,409.8100,2152.436533
9,0.624,0.470,0.759,0.680,0.368,3,14,0,23,10,...,0,NaN,1,1,1,3274.60250,7211.0,99288.0,2947.1375,3470.700000

In [3]:
df['gerouSinistro'].value_counts()

0    12043
1     9963
Name: gerouSinistro, dtype: int64

In [4]:
del df['renovou']
df.head(10)

,IDHM,IDHM_E,IDHM_L,IDHM_R,I_ESCOLARIDADE,Mes,anosFidelidadeCliente,codigoAgravamentoPremio,codigoCategoriaTarifaria,codigoClasseBonus,...,quantidadePortasVeiculo,quantidadeUtilizacaoEstapar,resgatePontos,sexoSegurado,tipoPessoaSegurado,valorDiferencaPremioAnual,valorFranquia,valorImportanciaSeguradaCasco,valorPremioFinal,valorPremioPagoAtual
0,0.578,0.363,0.730,0.729,0.365,3,2,0,10,10,...,5,0,0,1,1,933.00000,935.0,32076.0,839.7000,1263.210000
1,0.702,0.581,0.786,0.756,0.487,3,2,0,11,1,...,5,0,0,1,1,2022.98000,3480.0,20252.0,1921.8300,3850.400000
2,0.624,0.470,0.759,0.680,0.368,3,7,0,10,5,...,5,0,1,0,1,1680.48350,3870.0,19080.0,1571.2525,1825.660000
3,0.702,0.581,0.786,0.756,0.487,3,9,0,10,8,...,5,0,0,1,1,1796.34000,1884.0,42898.0,1796.3400,2554.540000
4,0.440,0.242,0.617,0.569,0.251,3,4,0,10,8,...,5,0,1,1,1,1223.12500,1847.0,36047.0,1131.3930,1241.230000
5,0.578,0.363,0.730,0.729,0.365,3,4,0,10,10,...,5,0,0,1,1,1276.10000,1954.0,60519.0,1276.1000,1434.400000
6,0.578,0.363,0.730,0.729,0.365,3,8,0,10,9,...,3,0,0,1,1,572.79000,1085.0,14588.0,515.5100,911.040000
7,0.783,0.719,0.845,0.789,0.629,3,1,0,11,0,...,4,2,0,0,0,5043.14000,4040.0,150325.0,4286.6700,4551.850000
8,0.702,0.581,0.786,0.756,0.487,3,1,0,23,10,...,5,0,0,1,1,1150.62038,4777.0,73399.0,409.8100,2152.436533
9,0.624,0.470,0.759,0.680,0.368,3,14,0,23,10,...,5,0,1,1,1,3274.60250,7211.0,99288.0,2947.1375,3470.700000

In [5]:
df.dtypes

IDHM                             float64
IDHM_E                           float64
IDHM_L                           float64
IDHM_R                           float64
I_ESCOLARIDADE                   float64
Mes                                int64
anosFidelidadeCliente              int64
codigoAgravamentoPremio            int64
codigoCategoriaTarifaria           int64
codigoClasseBonus                  int64
codigoClasseFranquia             float64
codigoClasseLocalizacao            int64
codigoCombustivelVeiculo           int64
codigoEstadoCivil                  int64
codigoFamiliaVeiculo               int64
codigoFormaPagamento               int64
codigoIBGEUF                       int64
codigoMarcaVeiculo                 int64
codigoSucursal                     int64
codigoTipoVeiculo                  int64
codigoUsoVeiculo                   int64
correntista                        int64
diaSemana                          int64
diferencaPremioAntNovo           float64
especieVeiculo                     int64
estacaoAno                         int64
faixaDiferencaValores              int64
faixaIdade                         int64
faixaPrecoFranquia                 int64
faixaPrecoLiquido                  int64
faixaPrecoPremioFinal              int64
gerouSinistro                      int64
numeroSegmentoCliente              int64
numeroSegmentoDocumento            int64
origemProposta                     int64
premioLiquidoPagoApolice         float64
quantidadeParcelas                 int64
quantidadePortasVeiculo            int64
quantidadeUtilizacaoEstapar        int64
resgatePontos                      int64
sexoSegurado                       int64
tipoPessoaSegurado                 int64
valorDiferencaPremioAnual        float64
valorFranquia                    float64
valorImportanciaSeguradaCasco    float64
valorPremioFinal                 float64
valorPremioPagoAtual             float64
dtype: object

In [6]:
Y = df['gerouSinistro'].values
del df['gerouSinistro']

X = df.values

In [7]:


from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_previsores = LabelEncoder()

#onehotencorder = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(), [1,3,5,6,7,8,9,13])],remainder='passthrough')
#X = onehotencorder.fit_transform(X).toarray()

labelencorder_classe = LabelEncoder()
Y = labelencorder_classe.fit_transform(Y)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [8]:
#Montando novo DataFrame com State, Churn e as colunas normalizadas na escala e Padronizadas
colunas = df.columns
df_new = pd.DataFrame (data=X, columns=colunas)
df_new['gerouSinistro'] = Y

df_new.head(10)

,IDHM,IDHM_E,IDHM_L,IDHM_R,I_ESCOLARIDADE,Mes,anosFidelidadeCliente,codigoAgravamentoPremio,codigoCategoriaTarifaria,codigoClasseBonus,...,quantidadeUtilizacaoEstapar,resgatePontos,sexoSegurado,tipoPessoaSegurado,valorDiferencaPremioAnual,valorFranquia,valorImportanciaSeguradaCasco,valorPremioFinal,valorPremioPagoAtual,gerouSinistro
0,-0.779790,-0.983587,-0.670102,0.002242,-0.807182,-0.539486,-0.731971,-0.119367,-0.553114,1.114251,...,-0.216676,-0.589910,1.123135,0.119534,-0.348239,-0.783023,-0.403773,-0.347005,-0.586918,0
1,0.419935,0.396310,0.225757,0.433966,0.187934,-0.539486,-0.731971,-0.119367,-0.407975,-1.216814,...,-0.216676,-0.589910,1.123135,0.119534,0.474509,0.454675,-0.684326,0.586720,1.011727,0
2,-0.334731,-0.306298,-0.206175,-0.781256,-0.782712,-0.539486,0.236975,-0.119367,-0.553114,-0.180785,...,-0.216676,1.695174,-0.890365,0.119534,0.215983,0.644342,-0.712135,0.284221,-0.239376,0
3,0.419935,0.396310,0.225757,0.433966,0.187934,-0.539486,0.624553,-0.119367,-0.553114,0.596237,...,-0.216676,-0.589910,1.123135,0.119534,0.303435,-0.321500,-0.146994,0.478440,0.211005,0
4,-2.114967,-1.749493,-2.477817,-2.556121,-1.737044,-0.539486,-0.344393,-0.119367,-0.553114,0.596237,...,-0.216676,1.695174,1.123135,0.119534,-0.129244,-0.339494,-0.309551,-0.095315,-0.600500,0
5,-0.779790,-0.983587,-0.670102,0.002242,-0.807182,-0.539486,-0.344393,-0.119367,-0.553114,1.114251,...,-0.216676,-0.589910,1.123135,0.119534,-0.089257,-0.287457,0.271107,0.029547,-0.481139,0
6,-0.779790,-0.983587,-0.670102,0.002242,-0.807182,-0.539486,0.430764,-0.119367,-0.553114,0.855244,...,-0.216676,-0.589910,1.123135,0.119534,-0.620136,-0.710074,-0.818719,-0.626735,-0.804527,0
7,1.203626,1.269822,1.169609,0.961628,1.346183,-0.539486,-0.925760,-0.119367,-0.407975,-1.475821,...,0.332178,-0.589910,-0.890365,-8.365829,2.754211,0.727017,2.401976,2.627241,1.445159,0
8,0.419935,0.396310,0.225757,0.433966,0.187934,-0.539486,-0.925760,-0.119367,1.333699,1.114251,...,-0.216676,-0.589910,1.123135,0.119534,-0.183973,1.085439,0.576717,-0.717939,-0.037458,0
9,-0.334731,-0.306298,-0.206175,-0.781256,-0.782712,-0.539486,1.593499,-0.119367,1.333699,1.114251,...,-0.216676,1.695174,1.123135,0.119534,1.419269,2.269155,1.190997,1.471415,0.777108,0

In [9]:
#Gravando os dados
df_new.to_csv('data/gincanaV1_SinistroTesteMarcio.csv', header=True, index=False)

In [10]:
df = pd.read_csv('data/gincanaV1_SinistroTesteMarcio.csv', sep=",")
df.head(10)

,IDHM,IDHM_E,IDHM_L,IDHM_R,I_ESCOLARIDADE,Mes,anosFidelidadeCliente,codigoAgravamentoPremio,codigoCategoriaTarifaria,codigoClasseBonus,...,quantidadeUtilizacaoEstapar,resgatePontos,sexoSegurado,tipoPessoaSegurado,valorDiferencaPremioAnual,valorFranquia,valorImportanciaSeguradaCasco,valorPremioFinal,valorPremioPagoAtual,gerouSinistro
0,-0.779790,-0.983587,-0.670102,0.002242,-0.807182,-0.539486,-0.731971,-0.119367,-0.553114,1.114251,...,-0.216676,-0.589910,1.123135,0.119534,-0.348239,-0.783023,-0.403773,-0.347005,-0.586918,0
1,0.419935,0.396310,0.225757,0.433966,0.187934,-0.539486,-0.731971,-0.119367,-0.407975,-1.216814,...,-0.216676,-0.589910,1.123135,0.119534,0.474509,0.454675,-0.684326,0.586720,1.011727,0
2,-0.334731,-0.306298,-0.206175,-0.781256,-0.782712,-0.539486,0.236975,-0.119367,-0.553114,-0.180785,...,-0.216676,1.695174,-0.890365,0.119534,0.215983,0.644342,-0.712135,0.284221,-0.239376,0
3,0.419935,0.396310,0.225757,0.433966,0.187934,-0.539486,0.624553,-0.119367,-0.553114,0.596237,...,-0.216676,-0.589910,1.123135,0.119534,0.303435,-0.321500,-0.146994,0.478440,0.211005,0
4,-2.114967,-1.749493,-2.477817,-2.556121,-1.737044,-0.539486,-0.344393,-0.119367,-0.553114,0.596237,...,-0.216676,1.695174,1.123135,0.119534,-0.129244,-0.339494,-0.309551,-0.095315,-0.600500,0
5,-0.779790,-0.983587,-0.670102,0.002242,-0.807182,-0.539486,-0.344393,-0.119367,-0.553114,1.114251,...,-0.216676,-0.589910,1.123135,0.119534,-0.089257,-0.287457,0.271107,0.029547,-0.481139,0
6,-0.779790,-0.983587,-0.670102,0.002242,-0.807182,-0.539486,0.430764,-0.119367,-0.553114,0.855244,...,-0.216676,-0.589910,1.123135,0.119534,-0.620136,-0.710074,-0.818719,-0.626735,-0.804527,0
7,1.203626,1.269822,1.169609,0.961628,1.346183,-0.539486,-0.925760,-0.119367,-0.407975,-1.475821,...,0.332178,-0.589910,-0.890365,-8.365829,2.754211,0.727017,2.401976,2.627241,1.445159,0
8,0.419935,0.396310,0.225757,0.433966,0.187934,-0.539486,-0.925760,-0.119367,1.333699,1.114251,...,-0.216676,-0.589910,1.123135,0.119534,-0.183973,1.085439,0.576717,-0.717939,-0.037458,0
9,-0.334731,-0.306298,-0.206175,-0.781256,-0.782712,-0.539486,1.593499,-0.119367,1.333699,1.114251,...,-0.216676,1.695174,1.123135,0.119534,1.419269,2.269155,1.190997,1.471415,0.777108,0

In [12]:
array = df.values
X = array[:,0:46]
Y = array[:,46]

#Gerando dados de Treino e de Teste para os modelos
from sklearn.model_selection import train_test_split

seed = 1313
X_treino, X_teste, y_treino, y_teste = train_test_split(X, Y, test_size = 0.30, random_state = seed)
Y

array([0., 0., 0., ..., 1., 1., 1.])

In [13]:
# Feature selection com Random Forest
from sklearn.ensemble import RandomForestClassifier 
from sklearn.feature_selection import SelectFromModel

clf = RandomForestClassifier(random_state=seed)
selector = clf.fit(X_treino, y_treino)
fs = SelectFromModel(selector, prefit=True)

X_treino_new = fs.transform(X_treino)
X_teste_new = fs.transform(X_teste)

print(X_treino_new.shape, X_teste_new.shape)

(15404, 16) (6602, 16)

In [15]:
mask = fs.get_support()
new_features = [] 
for bool, feature in zip(mask, colunas):
    if bool:
        new_features.append(feature)
        

df_selection = pd.DataFrame(X_treino_new, columns=new_features)
df_selection['gerouSinistro'] = y_treino
df_selection_teste = pd.DataFrame(X_teste_new, columns=new_features)
df_selection_teste['gerouSinistro'] = y_teste

df_selection_teste.head(10)

,IDHM_R,anosFidelidadeCliente,codigoClasseBonus,codigoClasseLocalizacao,codigoFamiliaVeiculo,codigoMarcaVeiculo,codigoSucursal,codigoTipoVeiculo,diaSemana,diferencaPremioAntNovo,premioLiquidoPagoApolice,valorDiferencaPremioAnual,valorFranquia,valorImportanciaSeguradaCasco,valorPremioFinal,valorPremioPagoAtual,gerouSinistro
0,0.961628,1.787288,1.114251,-0.408116,-1.096424,1.113908,-0.106449,-0.643553,-1.119427,-0.233141,0.154158,0.209830,-0.783023,0.095168,0.299288,-0.026383,1.0
1,0.002242,-0.731971,-1.216814,-0.164567,-0.899472,-0.649918,1.792347,1.906276,1.038053,0.557654,-0.500274,-0.303817,-0.446486,-0.489192,-0.241399,-0.054110,1.0
2,0.961628,0.043186,-0.439792,-0.529891,-1.227726,-0.649918,0.377558,1.850441,1.577423,-0.197090,-0.269297,0.007655,-0.453781,-0.488219,0.037321,-0.378405,1.0
3,0.961628,1.205921,0.855244,-0.408116,0.610496,1.609017,-0.106449,-0.736613,-0.040687,0.091673,-0.204393,-0.139334,0.961912,0.344378,-0.132079,-0.117747,0.0
4,0.433966,-0.150604,0.596237,-0.408116,1.070052,1.299574,0.563714,-0.643553,1.577423,1.385077,0.991542,0.816182,0.918143,-0.257825,1.251483,1.856426,1.0
5,-0.525420,-0.538182,-1.475821,-0.408116,-1.096424,1.609017,-1.335082,-0.624941,-0.040687,-0.292874,-0.319514,0.049880,0.469265,-0.292918,-0.000420,-0.490432,1.0
6,0.002242,1.012131,1.114251,0.809630,-1.096424,1.299574,-1.223388,-0.476046,1.577423,-0.253823,-0.591791,-0.245703,-0.483446,-0.123670,-0.259960,-0.705631,0.0
7,0.433966,-0.731971,-1.475821,-0.773440,-0.899472,-0.588029,-1.111694,-0.476046,-0.040687,-1.926390,1.901845,-2.749067,-0.376941,0.290825,-2.001388,0.341680,0.0
8,0.529905,-0.344393,1.114251,2.879799,1.135703,-0.371419,-0.962769,-0.234092,1.038053,-0.125911,-0.366050,-0.154912,-0.096331,-0.154929,-0.199413,-0.414627,1.0
9,0.433966,3.337601,1.114251,-0.408116,-1.096424,-0.495196,0.265864,-0.438822,-1.658797,-0.815231,1.155285,0.868235,-0.419738,-0.380947,1.124073,0.456877,1.0

In [16]:
df_selection.to_csv('data/gincanaV1_SinistroTreino.csv', header=True, index=False)
df_selection_teste.to_csv('data/gincanaV1_SinistroTeste.csv', header=True, index=False)